- title: Language Structure
  id: language
  part: true
  children:
    - title: Keywords
      content:
        - source: doc/keywords.md
    - title: Syntax
      id: syntax
      content:
        - source: doc/syntax.md
      children:
        - title: Literals
          content:
            # TODO: Update/rewrite accordingly to our structure
            - source: doc/syntax/literals.md
        - title: Assignment
          content:
            - source: doc/syntax/assignment.md
        - title: Expressions
          content:
            - source: doc/syntax/control_expressions.md
          children:
            - title: Precedence
              content:
                - source: doc/syntax/precedence.md
        - title: Defining methods
          id: methods-def
          content:
            - source: doc/syntax/methods.md
        - title: Calling methods
          id: methods-call
          content:
            - source: doc/syntax/calling_methods.md
        - title: Modules and Classes
          content:
            - source: doc/syntax/modules_and_classes.md
        - title: Exceptions
          content:
            - source: doc/syntax/exceptions.md
        - title: Refinements
          content:
            - source: doc/syntax/refinements.md
    - title: Globals
      content:
        - source: doc/globals.md
- title: Built-in Classes
  part: true
  id: builtin
  children:
    - title: Language Core
      id: core
      content:
        - source: content/core/core.md
        - source: core/Kernel.md
        - source: core/BasicObject.md
        - source: core/Object.md
        - source: core/Module.md
        - source: core/Class.md
        - source: core/Method.md
        - source: core/UnboundMethod.md
        - source: core/Proc.md
        - source: core/Fiber.md
        - source: core/Binding.md
        # Deprecated/obsolete, see https://bugs.ruby-lang.org/issues/10548
        # - source: core/Continuation.md

    - title: Data Types
      id: types
      content:
        - source: content/core/types.md
        - source: core/TrueClass.md
        - source: core/FalseClass.md
        - source: core/NilClass.md
        - source: core/Comparable.md
      children:
        - title: Numbers
          content:
            - source: core/Numeric.md
            - source: core/Integer.md
            - source: core/Float.md
            - source: core/Rational.md
            - source: core/Complex.md
            # TODO: notice about bigdecimal
            - source: core/Math.md
        - title: Symbols and strings
          content:
            - source: core/Symbol.md
            - source: core/String.md
          children:
            - title: Encodings
              content:
                - source: core/Encoding.md
                # Nothing documented there
                # - source: core/UnicodeNormalize.md
        - title: Regular expressions
          id: regexp
          content:
            - source: core/Regexp.md
            - source: core/MatchData.md
            # Just mentioning it here, but it is already included in Regexp docs by RDoc means
            # - source: doc/regexp.md
        - title: Range
          content:
            - source: core/Range.md
        - title: Struct
          content:
            - source: core/Struct.md
        - title: Time
          content:
            - source: core/Time.md
            # TODO: notice about time.rb & Date

        - title: Collections
          content:
            - source: content/core/collections.md
            - source: core/Enumerable.md
            - source: core/Enumerator.md
          children:
            - title: Array
              content:
                - source: core/Array.md
            - title: Hash
              content:
                - source: core/Hash.md

    - title: Exceptions
      content:
        # Order and depth here are corresponding to explanation in Exception class docs
        - source: core/Exception.md
        - source: core/NoMemoryError.md
        - source: core/ScriptError.md
        - source: core/LoadError.md
          header_shift: 2
        - source: core/NotImplementedError.md
          header_shift: 2
        - source: core/SyntaxError.md
          header_shift: 2
        - source: core/SecurityError.md
        - source: core/SignalException.md
        - source: core/Interrupt.md
          header_shift: 2
        - source: core/StandardError.md
        - source: core/ArgumentError.md
          header_shift: 2
        - source: core/UncaughtThrowError.md
          header_shift: 3
        - source: core/EncodingError.md
          header_shift: 2
        - source: core/FiberError.md
          header_shift: 2
        - source: core/IOError.md
          header_shift: 2
        - source: core/EOFError.md
          header_shift: 3
        - source: core/IndexError.md
          header_shift: 2
        - source: core/KeyError.md
          header_shift: 3
        - source: core/StopIteration.md
          header_shift: 3
        - source: core/LocalJumpError.md
          header_shift: 2
        - source: core/NameError.md
          header_shift: 2
        - source: core/NoMethodError.md
          header_shift: 3
        - source: core/RangeError.md
          header_shift: 2
        - source: core/FloatDomainError.md
          header_shift: 3
        - source: core/RegexpError.md
          header_shift: 2
        - source: core/RuntimeError.md
          header_shift: 2
        - source: core/FrozenError.md
          header_shift: 3
        - source: core/SystemCallError.md
          header_shift: 2
        - source: core/Errno.md
          header_shift: 3
        - source: core/ThreadError.md
          header_shift: 2
        - source: core/TypeError.md
          header_shift: 2
        - source: core/ZeroDivisionError.md
          header_shift: 2
        - source: core/SystemExit.md
        - source: core/SystemStackError.md
        - source: core/fatal.md
        # Definition is empty
        # - source: core/ClosedQueueError.md

    - title: Concurrency and Parallelism
      content:
        - source: core/Thread.md
        - source: core/ThreadGroup.md
        - source: core/Mutex.md
        - source: core/ConditionVariable.md
          header_shift: 2
        - source: core/Queue.md
        - source: core/SizedQueue.md
          header_shift: 2

    - title: Filesystem and Environment
      content:
        # TODO: Structure it somehow!
        - source: core/ARGF.md
        - source: core/Dir.md
        - source: core/ENV.md
        - source: core/FileTest.md
        - source: core/File--Constants.md
        - source: core/File.md
        - source: core/IO.md
      children:
        - title: Processes and Signals
          content:
            - source: core/Process.md
            - source: core/Signal.md

    - title: Language Internals
      id: internals
      content:
        # TODO: some intro, or at least title
        - source: core/ObjectSpace.md
        - source: core/GC.md
        - source: core/TracePoint.md
        # TODO: RubyVM::InstructionSequence have some docs!
        # - source: core/RubyVM.md
    - title: Marshal
      content:
        - source: core/Marshal.md
        - source: doc/marshal.md
    - title: Misc
      content:
        - source: core/Random.md
        - source: core/Warning.md
        # deprecated
        # - source: core/Data.md
