- title: Language Structure
  id: language
  part: true
  children:
    - title: Keywords
      content:
        - source: doc/keywords.md
    - title: Syntax
      id: syntax
      content:
        - source: doc/syntax.md
      children:
        - title: Literals
          content:
            # TODO: Update/rewrite accordingly to our structure
            - source: doc/syntax/literals.md
        - title: Assignment
          content:
            - source: doc/syntax/assignment.md
        - title: Expressions
          content:
            - source: doc/syntax/control_expressions.md
          children:
            - title: Precedence
              content:
                - source: doc/syntax/precedence.md
        - title: Defining methods
          id: methods-def
          content:
            - source: doc/syntax/methods.md
        - title: Calling methods
          id: methods-call
          content:
            - source: doc/syntax/calling_methods.md
        - title: Modules and Classes
          content:
            - source: doc/syntax/modules_and_classes.md
        - title: Exceptions
          content:
            - source: doc/syntax/exceptions.md
        - title: Refinements
          content:
            - source: doc/syntax/refinements.md
    - title: Globals
      content:
        - source: doc/globals.md
        - source: lib/English/English.md
- title: Built-in Classes
  part: true
  id: builtin
  children:
    - title: Language Core
      id: core
      content:
        - source: content/core/core.md
        - source: core/Kernel.md
        - source: core/BasicObject.md
        - source: core/Object.md
        - source: core/Module.md
        - source: core/Class.md
        - source: core/Method.md
        - source: core/UnboundMethod.md
        - source: core/Proc.md
        - source: core/Fiber.md
        - source: core/Binding.md
        # Deprecated/obsolete, see https://bugs.ruby-lang.org/issues/10548
        # - source: core/Continuation.md

    - title: Data Types
      id: types
      content:
        - source: content/core/types.md
        - source: core/TrueClass.md
        - source: core/FalseClass.md
        - source: core/NilClass.md
        - source: core/Comparable.md
      children:
        - title: Numbers
          content:
            - source: core/Numeric.md
            - source: core/Integer.md
            - source: core/Float.md
            - source: core/Rational.md
            - source: core/Complex.md
            # TODO: notice about bigdecimal
            - source: core/Math.md
        - title: Symbols and strings
          content:
            - source: core/Symbol.md
            - source: core/String.md
          children:
            - title: Encodings
              content:
                - source: core/Encoding.md
                # Nothing documented there
                # - source: core/UnicodeNormalize.md
        - title: Regular expressions
          id: regexp
          content:
            - source: core/Regexp.md
            - source: core/MatchData.md
            # Just mentioning it here, but it is already included in Regexp docs by RDoc means
            # - source: doc/regexp.md
        - title: Range
          content:
            - source: core/Range.md
        - title: Struct
          content:
            - source: core/Struct.md
        - title: Time
          content:
            - source: core/Time.md
            # TODO: notice about time.rb & Date
            - source: lib/time/Time.md
        - title: Collections
          content:
            - source: content/core/collections.md
            - source: core/Enumerable.md
            - source: core/Enumerator.md
          children:
            - title: Array
              content:
                - source: core/Array.md
            - title: Hash
              content:
                - source: core/Hash.md

    - title: Exceptions
      content:
        # Order and depth here are corresponding to explanation in Exception class docs
        - source: core/Exception.md
        - source: core/NoMemoryError.md
        - source: core/ScriptError.md
        - source: core/LoadError.md
          header_shift: 2
        - source: core/NotImplementedError.md
          header_shift: 2
        - source: core/SyntaxError.md
          header_shift: 2
        - source: core/SecurityError.md
        - source: core/SignalException.md
        - source: core/Interrupt.md
          header_shift: 2
        - source: core/StandardError.md
        - source: core/ArgumentError.md
          header_shift: 2
        - source: core/UncaughtThrowError.md
          header_shift: 3
        - source: core/EncodingError.md
          header_shift: 2
        - source: core/FiberError.md
          header_shift: 2
        - source: core/IOError.md
          header_shift: 2
        - source: core/EOFError.md
          header_shift: 3
        - source: core/IndexError.md
          header_shift: 2
        - source: core/KeyError.md
          header_shift: 3
        - source: core/StopIteration.md
          header_shift: 3
        - source: core/LocalJumpError.md
          header_shift: 2
        - source: core/NameError.md
          header_shift: 2
        - source: core/NoMethodError.md
          header_shift: 3
        - source: core/RangeError.md
          header_shift: 2
        - source: core/FloatDomainError.md
          header_shift: 3
        - source: core/RegexpError.md
          header_shift: 2
        - source: core/RuntimeError.md
          header_shift: 2
        - source: core/FrozenError.md
          header_shift: 3
        - source: core/SystemCallError.md
          header_shift: 2
        - source: core/Errno.md
          header_shift: 3
        - source: core/ThreadError.md
          header_shift: 2
        - source: core/TypeError.md
          header_shift: 2
        - source: core/ZeroDivisionError.md
          header_shift: 2
        - source: core/SystemExit.md
        - source: core/SystemStackError.md
        - source: core/fatal.md
        # Definition is empty
        # - source: core/ClosedQueueError.md

    - title: Concurrency and Parallelism
      content:
        - source: core/Thread.md
        - source: core/ThreadGroup.md
        - source: core/Mutex.md
        - source: core/ConditionVariable.md
          header_shift: 2
        - source: core/Queue.md
        - source: core/SizedQueue.md
          header_shift: 2

    - title: Filesystem and Environment
      content:
        # TODO: Structure it somehow!
        - source: core/ARGF.md
        - source: core/Dir.md
        - source: core/ENV.md
        - source: core/FileTest.md
        - source: core/File--Constants.md
        - source: core/File.md
        - source: core/IO.md
      children:
        - title: Processes and Signals
          content:
            - source: core/Process.md
            - source: core/Signal.md

    - title: Language Internals
      id: internals
      content:
        # TODO: some intro, or at least title
        - source: core/ObjectSpace.md
        - source: ext/objspace/ObjectSpace.md
          header_shift: 2
        - source: core/GC.md
        - source: core/TracePoint.md
        # TODO: RubyVM::InstructionSequence have some docs!
        # - source: core/RubyVM.md
    - title: Marshal
      content:
        - source: core/Marshal.md
        - source: doc/marshal.md
    - title: Misc
      content:
        - source: core/Random.md
        - source: core/Warning.md
        # deprecated
        # - source: core/Data.md

- title: Standard Library
  part: true
  id: stdlib
  children:
    # TODO: Intro explaining the structure of docs
    - title: Data Types
      id: types
      content:
        - source: "# Data Types"
      children:
        - title: Bigdecimal
          content:
            - source: ext/bigdecimal/BigDecimal.md
            # - source: ext/bigdecimal/BigMath.md
            # - source: ext/bigdecimal/Jacobian.md
            # - source: ext/bigdecimal/LUSolve.md
            # - source: ext/bigdecimal/Newton.md
        - title: Set
          content:
          - source: lib/set/Set.md
          - source: lib/set/SortedSet.md
        - title: Matrix
          content:
            - source: lib/matrix/Matrix.md
            - source: lib/matrix/Vector.md
        - title: Date
          content:
            - source: ext/date/Date.md
            - source: ext/date/DateTime.md
        - title: OpenStruct
          content:
            - source: lib/ostruct/OpenStruct.md

    - title: Design Patterns
      id: patterns
      content:
        - source: "# Ruby implementation of common design patterns"
      children:
        - title: Forwardable
          content:
            - source: lib/forwardable/Forwardable.md
            - source: lib/forwardable/SingleForwardable.md
        - title: Delegator
          content:
            - source: lib/delegate/Delegator.md
            - source: lib/delegate/SimpleDelegator.md
        - title: Observable
          content:
            - source: lib/observer/Observable.md
        - title: Singleton
          content:
            - source: lib/singleton/Singleton.md

    - title: Formats
      content:
        - source: content/stdlib/formats.md
      children:
        - title: CSV
          content:
            - source: lib/csv/CSV.md
        - title: JSON
          content:
            - source: ext/json/JSON.md
            # - source: ext/json/Class.md
        - title: YAML
          content:
            - source: lib/yaml/YAML.md
            - source: ext/psych/Psych.md
        - title: XML
          content:
            - source: lib/rexml/REXML.md
            - source: lib/rss/RSS.md
        - title: Zlib
          content:
            - source: ext/zlib/Zlib.md

    - title: Development and Debugging
      content:
        - source: >
            # Development and Debuggin Tools

            This section lists several tools that help developing in Ruby.
        - source: lib/benchmark/Benchmark.md
        - source: lib/debug/DEBUGGER__.md
        - source: ext/coverage/Coverage.md
        - source: lib/pp/PP.md
        - source: lib/prettyprint/PrettyPrint.md
        - source: lib/profiler/Profiler__.md
        - source: lib/tracer/Tracer.md
        - source: lib/logger/Logger.md
        - source: ext/ripper/Ripper.md
        # - source: ext/ripper/DSL.md
        - source: lib/racc/Racc.md
        - source: ext/fiddle/Fiddle.md

    - title: String Utilities
      content:
        - source: lib/scanf/Scanf.md
        - source: lib/abbrev/Abbrev.md
        - source: ext/stringio/StringIO.md
        - source: ext/strscan/StringScanner.md

    - title: Networking and Web
      content:
        - source: lib/cgi/CGI.md
        - source: lib/uri/URI.md
        - source: lib/open-uri/OpenURI.md
        - source: lib/ipaddr/IPAddr.md
        - source: lib/webrick/WEBrick.md
        # - source: lib/webrick/Errno.md
        - source: ext/socket/Socket.md
        # - source: ext/socket/Addrinfo.md
        # - source: ext/socket/BasicSocket.md
        # - source: ext/socket/IPSocket.md
        # - source: ext/socket/SOCKSSocket.md
        # - source: ext/socket/SocketError.md
        # - source: ext/socket/TCPServer.md
        # - source: ext/socket/TCPSocket.md
        # - source: ext/socket/UDPSocket.md
        # - source: ext/socket/UNIXServer.md
        # - source: ext/socket/UNIXSocket.md

    - title: File Utilities
      content:
        - source: ext/pathname/Pathname.md
        - source: lib/tempfile/Tempfile.md
        - source: lib/fileutils/FileUtils.md
        - source: lib/find/Find.md

    - title: System Programming and Console
      content:
        - source: lib/shell/Shell.md
        - source: lib/optparse/OptionParser.md
        - source: ext/etc/Etc.md
        - source: ext/pty/PTY.md
        # - source: ext/pty/IO.md
        - source: ext/fcntl/Fcntl.md
        - source: ext/readline/Readline.md
        - source: ext/win32ole/WIN32OLE.md
        - source: ext/syslog/Syslog.md
        - source: lib/open3/Open3.md
        # - source: ext/win32ole/IE_CONST.md
        # - source: ext/win32ole/IXMLDOMNode.md
        # - source: ext/win32ole/IXMLDOMParseError.md
        # - source: ext/win32ole/IXMLHttpRequest.md
        # - source: ext/win32ole/IXTLRuntime.md
        # - source: ext/win32ole/Microsoft_FreeThreadedXMLDOM_1_0.md
        # - source: ext/win32ole/Microsoft_XMLDOM_1_0.md
        # - source: ext/win32ole/Microsoft_XMLDSO_1_0.md
        # - source: ext/win32ole/Microsoft_XMLHTTP_1.md
        # - source: ext/win32ole/Msxml.md
        # - source: ext/win32ole/OLEProperty.md
        # - source: ext/win32ole/OLEtagDOMNodeType.md
        # - source: ext/win32ole/OLEtagXMLEMEM_TYPE.md
        # - source: ext/win32ole/WIN32OLERuntimeError.md
        # - source: ext/win32ole/WIN32OLE_EVENT.md
        # - source: ext/win32ole/WIN32OLE_METHOD.md
        # - source: ext/win32ole/WIN32OLE_PARAM.md
        # - source: ext/win32ole/WIN32OLE_RECORD.md
        # - source: ext/win32ole/WIN32OLE_TYPE.md
        # - source: ext/win32ole/WIN32OLE_TYPELIB.md
        # - source: ext/win32ole/WIN32OLE_VARIABLE.md
        # - source: ext/win32ole/WIN32OLE_VARIANT.md

    - title: Misc Utilities
      id: misc
      content:
      - source: lib/prime/Prime.md
      - source: lib/securerandom/SecureRandom.md
      - source: lib/timeout/Timeout.md
      # - source: lib/timeout/Timeout--TimeoutError.md

    - title: Cryptography and Encoding
      content:
        - source: lib/base64/Base64.md
        - source: ext/digest/Digest.md
        - source: ext/openssl/OpenSSL.md

    - title: Concurrency Utils
      content:
        - source: lib/monitor/Monitor.md
        - source: lib/monitor/MonitorMixin.md
        - source: lib/mutex_m/Mutex_m.md
        - source: lib/sync/Sync.md
        - source: lib/sync/Sync_m.md
        - source: lib/sync/Synchronizer.md
        - source: lib/sync/Synchronizer_m.md

    - title: Other Libraries
      id: other
      content:
        - source: lib/cmath/CMath.md
        - source: ext/dbm/DBM.md
        # - source: ext/dbm/DBMError.md
        - source: ext/gdbm/GDBM.md
        - source: ext/nkf/NKF.md
        # - source: ext/nkf/Kconv.md
        - source: ext/sdbm/SDBM.md
        # - source: ext/sdbm/SDBMError.md
        - source: lib/getoptlong/GetoptLong.md
        - source: lib/drb/DRb.md
        # - source: lib/drb/ACL.md
        # - source: lib/drb/DRb--DRbIdConv.md
        # - source: lib/drb/DRb--DRbObject.md
        # - source: lib/drb/DRb--DRbUndumped.md
        - source: lib/e2mmap/Exception2MessageMapper.md
        - source: lib/rinda/Rinda.md
        - source: lib/resolv/Resolv.md
        - source: lib/shellwords/Shellwords.md
        - source: lib/thwait/ThreadsWait.md
        # - source: lib/thwait/ThWait.md
        - source: lib/tsort/TSort.md
        - source: lib/weakref/WeakRef.md
        - source: lib/pstore/PStore.md
        # - source: ext/win32/Win32.md

# Will go to other sections:
# - source: lib/irb/IRB.md
# - source: lib/irb/XMP.md
# - source: lib/rdoc/RDoc.md
# - source: lib/rubygems/Gem.md
# - source: lib/rubygems/Kernel.md
# - source: lib/rubygems/TempIO.md
# - source: lib/rubygems/YAML--Syck.md
# - source: lib/mkmf/MakeMakefile.md
